name: Deploy File

on:
  push:
    branches: [main]

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2

      - name: Upload file to S3
        uses: actions/checkout@v4
        with:
          sparse-checkout: s3
      - run: aws s3 cp s3/file.json s3://${{ secrets.S3_BUCKET_NAME }}/llm_info.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_UPLOAD_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_UPLOAD_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
